freinds_details=[{
    "name":"Murugeswari",
    "place":"Krishnancoil",
    "hobbies":["drawing","gardening","reading"]
},    
{
    "name":"rofiya",
    "place":"vadasery",
    "hobbies":["listeningmusic","reading","sleeping"]
},    
{
    "name":"jeswin",
    "place":"parakai",
    "hobbies":["bikeriding","handball","movies"]
},
{
    "name":"ramkarthick",
    "place":"krishnancoil",
    "hobbies":["gym","roaming","movies"]
},
{
    "name":"kumari",
    "place":"maroongur",
    "hobbies":["movies","reading","music"]
},
{
    "name":"lingam",
    "place":"rosmiyapuram",
    "hobbies":["movies","music","travelling"]
},
{
    "name":"saravanan",
    "place":"manalikarai",
    "hobbies":["games","movies","games"]
}]
print(freinds_details[0]["hobbies"])
print(freinds_details[0]["place"])
#print

"""
friends_names=["Murugeswari","Rofiya","jeswin","ramkarthick","kumari","lingam","saravanan"]
print(friends_names)
#print
"""

"""
my_details={
    "name":"sangee",
    "place":"vadasery",
    "number":100
}
print(my_details)
"""
"""
my_resume=[{
    "name":"sangeeetha",
    "email":"sangeethakesavan76@gmail.com",
    "mobile-no":9344565704,
    "softskills":["comunicationskills","selfmotivation"],
    "hardskills":["typewritting","msoffice"],
    "educationalqualifiation":["sslc","hsc","b.com"],
    "project":"role of women entreprenur change in the society",
    "hobbies":["reading","editing","designing"],
    "personaldetails":{ 
        "fathername":"kesavan",
        "fathersoccupation":"salesman",
        "languagesknown":["tamil","english"],
        "dob":"21/07/2003",
        "gender":"female",
        "materialstatus":"single",
        "address":"45 thazhuviya mahadevar kovil street"
}}]
print(my_resume)
print(my_resume[0]["personaldetails"]["fathername"])
print(my_resume[0]["mobile-no"])
"""